name: Deploy to AWS
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: npm install

