name: Deploy to AWS
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: npm install
    - name: Build backend
      run: npm run build-backend
    - name: Build frontend
      run: npm run build-frontend
    - name: Generate zip package
      run: zip -r paketti.zip . -x '*.git*'
    - name: Deploy package to AWS
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Risbeegomfkerho
        environment_name: Risbeegomfkerho-env
        use_existing_version_if_available: true
        region: us-east-2
        deployment_package: paketti.zip 

