name: Koodin tsekkaus
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  Koodin_tarkastus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: npm asennus
      run: npm install
    - name: back- ja frontendin rakennus
      run: npm run build
    - name: linttaus
      run: npm run lint
    - name: frontend test
      run: npm run test:frontend
    - name: e2e testi
      uses: cypress-io/github-action@v2
      env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
      with:
        start: npm run start
        install: false
        spec: cypress/integration/*
        wait-on: http://localhost:8080
        wait-on-timeout: 60
        
   
    